-- AURA // NØIR: esquema inicial para Supabase (PostgreSQL)
-- Pega TODO este archivo en Supabase > SQL Editor > New query y pulsa Run.
-- Permisos: el navegador puede leer el catálogo, pero no editar productos ni stock.

create table if not exists public.categorias (
  id_categoria bigint generated by default as identity primary key,
  nombre text not null unique,
  descripcion text
);
create table if not exists public.proveedores (
  id_proveedor bigint generated by default as identity primary key,
  nombre_empresa text not null, contacto text, telefono text, email text
);
create table if not exists public.productos (
  id_producto bigint generated by default as identity primary key,
  nombre text not null, descripcion text, precio numeric(10,2) not null check (precio >= 0),
  stock integer not null default 0 check (stock >= 0),
  id_categoria bigint not null references public.categorias(id_categoria),
  id_proveedor bigint not null references public.proveedores(id_proveedor),
  imagen text
);

insert into public.categorias (id_categoria, nombre, descripcion) values
 (1, 'Titanio', 'Prendas estructurales y de estética metálica.'),
 (2, 'Neopreno', 'Prendas técnicas y de alto rendimiento.'),
 (3, 'Seda técnica', 'Prendas ligeras de acabado premium.')
on conflict (id_categoria) do update set nombre=excluded.nombre, descripcion=excluded.descripcion;
insert into public.proveedores (id_proveedor, nombre_empresa, contacto, telefono, email) values
 (1, 'AURA // NØIR Atelier', 'Departamento de producción', '3000000000', 'atelier@auranoir.com'),
 (2, 'NØIR Materials', 'Departamento de materiales', '3000000001', 'materials@auranoir.com')
on conflict (id_proveedor) do update set nombre_empresa=excluded.nombre_empresa, contacto=excluded.contacto, telefono=excluded.telefono, email=excluded.email;
insert into public.productos (id_producto, nombre, descripcion, precio, stock, id_categoria, id_proveedor, imagen) values
 (1, 'CHAQUETA VORONOI', 'Chaqueta escultórica de corte estructural.', 350000, 10, 1, 1, 'img/chaqueta-voronoi.jpg'),
 (2, 'PANTALÓN TECTÓNICO', 'Pantalón técnico de silueta arquitectónica.', 280000, 8, 1, 1, 'img/pantalon-tectonico.jpg'),
 (3, 'BOMBER KINÉTICA', 'Bomber técnica de volumen contemporáneo.', 420000, 5, 2, 1, 'img/bomber-kinetica.jpg'),
 (4, 'BOTAS EXOESQUELETO', 'Botas de estética futurista y construcción robusta.', 390000, 6, 1, 2, 'img/botas-exoesqueleto.jpg'),
 (5, 'TOP VECTOR', 'Top técnico de líneas minimalistas.', 180000, 12, 2, 2, 'img/top-vector.jpg'),
 (6, 'FALDA ÓRBITA', 'Falda de estructura asimétrica.', 240000, 7, 3, 1, 'img/falda-orbita.jpg'),
 (7, 'CAMISA NEXO', 'Camisa ligera de inspiración industrial.', 210000, 9, 3, 1, 'img/camisa-nexo.jpg'),
 (8, 'PANTALÓN FASE', 'Pantalón técnico de líneas limpias.', 295000, 11, 2, 2, 'img/pantalon-fase.jpg')
on conflict (id_producto) do update set nombre=excluded.nombre, descripcion=excluded.descripcion, precio=excluded.precio, stock=excluded.stock, id_categoria=excluded.id_categoria, id_proveedor=excluded.id_proveedor, imagen=excluded.imagen;

select setval(pg_get_serial_sequence('public.categorias','id_categoria'), greatest((select coalesce(max(id_categoria),1) from public.categorias),1), true);
select setval(pg_get_serial_sequence('public.proveedores','id_proveedor'), greatest((select coalesce(max(id_proveedor),1) from public.proveedores),1), true);
select setval(pg_get_serial_sequence('public.productos','id_producto'), greatest((select coalesce(max(id_producto),1) from public.productos),1), true);

alter table public.categorias enable row level security;
alter table public.proveedores enable row level security;
alter table public.productos enable row level security;
drop policy if exists "Lectura pública de categorías" on public.categorias;
create policy "Lectura pública de categorías" on public.categorias for select to anon, authenticated using (true);
drop policy if exists "Lectura pública de proveedores" on public.proveedores;
create policy "Lectura pública de proveedores" on public.proveedores for select to anon, authenticated using (true);
drop policy if exists "Lectura pública de productos" on public.productos;
create policy "Lectura pública de productos" on public.productos for select to anon, authenticated using (true);
grant select on public.categorias, public.proveedores, public.productos to anon, authenticated;
